companies:
    # - CêlaVíta: {
    #     omzet: 45700000
    #     winst: 325932
    #     activa: '39200000'
    #     kvk: '081290200000'
    #     adres: '8090 AA WEZEP'
    #     werknemers: '200 t/m 499'
    # }
    - CêlaVíta
    - Abbott
    - Zehnder
    - Heuver
    - Ikea
    - Bakkerij Fuite
    - CêlaVíta
    - Scania
    - Broshuis Beheer
    - Reginox
    - Veneta
    - Thomassen
    - Visser Duiven
    - Westerman Logistics
    - TrafficSupply
    - Roelofs Internationaal Transport